opensearch_version: 3.x
cluster_name: testing-os
opensearch_admin_password: admin-test
opensearch_initialization: false
heap_size: 4g

seed_hosts:
master_nodes:

opensearch_config:
  template: opensearch.yaml.j2
  dest: /etc/opensearch/opensearch.yaml
  owner: root
  group: opensearch
  mode: "0640"

network:
  host: 0.0.0.0
  http_port: 9200
  transport_port: 9300
